{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tracey-shop.serviceAccountName" . }}
  labels:
    {{- include "tracey-shop.labels" . | nindent 4 }}
{{- end }}
